from enum import Enum


class BeatstatsGenre(Enum):
    TECHNO_PEAK_TIME = '6'
    TECHNO_RAW_DEEP_HYPNOTIC = '92'
    TRANCE_RAW_DEEP_HYPNOTIC = '99'
    PROGRESSIVE_HOUSE = '15' # a voir
    MELODIC_HOUSE_TECHNO = '90'
    HYPE_TECHNO_PEAK_TIME = '1006'
    HYPE_MELODIC_HOUSE_TECHNO = '1090'
